import { mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

// Regression coverage for the CRLF defect that broke the `lint` gate
// (`prettier --check` rejected 64 files whose only defect was CRLF line
// endings — see .gitattributes and T-001 finding A-001). `.gitattributes`
// (`eol=lf`) is the durable fix; this spec is the durable guard against it
// recurring, matching the standard `tests/boundaries/boundaries.spec.ts` and
// `tests/boundaries/lint-boundaries.spec.ts` already set: a check that
// cannot fail proves nothing, so a synthetic-CRLF control accompanies the
// real assertion.
//
// Deliberately does not use `git ls-files`: git is inoperable inside the
// agent container (`fatal: not a git repository` — the worktree's `.git`
// points at an unmounted Windows host path). The filesystem is walked
// directly instead.

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../..');

// Mirrors the exclusion list used by the one-shot normalisation pass, plus
// the directories those tools themselves live under.
const EXCLUDE_DIRS = new Set([
  'node_modules',
  '.pnpm-store',
  'dist',
  'dist-types',
  'coverage',
  'playwright-report',
  'test-results',
  '.vite',
  '.git',
  '.harness',
]);

// `.devcontainer/devcontainer.json` is regenerated by the harness at
// container start from a Windows host, so it carries CRLF endings that this
// repository does not control and cannot durably fix (its mtime post-dates
// every repo file and it is rewritten on every container start). It is
// already out of `prettier --check`'s scope via `.prettierignore:19`, so
// this walk's scope must match the lint gate's scope rather than exceed it.
const EXCLUDE_FILES = new Set(['.devcontainer/devcontainer.json']);

const BINARY_EXT = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.woff',
  '.woff2',
  '.ttf',
  '.otf',
  '.mp4',
  '.zip',
  '.gz',
  '.pdf',
  '.bsp',
]);

interface WalkResult {
  /** Repo-relative paths of text files that contain at least one CR byte. */
  offenders: string[];
  /** Number of files walked (sanity check that the walk found real files). */
  scanned: number;
}

function walk(dir: string, result: WalkResult): void {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry)) continue;
      walk(full, result);
      continue;
    }
    if (!st.isFile()) continue;
    if (entry.endsWith('.tsbuildinfo')) continue;
    if (EXCLUDE_FILES.has(path.relative(repoRoot, full).split(path.sep).join('/'))) continue;

    const ext = path.extname(entry).toLowerCase();
    if (BINARY_EXT.has(ext)) continue;

    const buf = readFileSync(full);
    // Skip anything binary that isn't caught by extension — a NUL byte
    // cannot occur in valid UTF-8/ASCII text, so this can never flag a
    // legitimate source or doc file, only assets added later without a
    // matching extension rule above.
    if (buf.includes(0)) continue;

    result.scanned += 1;
    if (buf.includes(0x0d)) {
      result.offenders.push(path.relative(repoRoot, full));
    }
  }
}

describe('repository text files use LF line endings (.gitattributes eol=lf)', () => {
  it('no tracked text file contains a CR byte', () => {
    const result: WalkResult = { offenders: [], scanned: 0 };
    walk(repoRoot, result);

    // Sanity check the walk actually visited the repository, not an empty
    // directory — otherwise an empty `offenders` array would be a false
    // pass.
    expect(result.scanned).toBeGreaterThan(50);

    expect(result.offenders, `CRLF/CR found in:\n  ${result.offenders.join('\n  ')}`).toEqual([]);
  });

  it('control: a synthetic CRLF fixture is detected by the same walk', () => {
    const scratchDir = mkdtempSync(path.join(tmpdir(), 'nova-line-endings-control-'));
    try {
      const fixture = path.join(scratchDir, 'crlf-fixture.ts');
      writeFileSync(fixture, 'export const x = 1;\r\n', 'utf8');

      const result: WalkResult = { offenders: [], scanned: 0 };
      walk(scratchDir, result);

      expect(result.scanned).toBe(1);
      expect(result.offenders).toEqual([path.relative(repoRoot, fixture)]);
    } finally {
      rmSync(scratchDir, { recursive: true, force: true });
    }
  });
});
